language: python
python:
- '2.7'

install:
- pip install -r test-requirements.txt
- pip install coveralls
- pip install pyflakes==1.2.3
- pip install pylint==1.5.6
- pip install yapf==0.10.0
- pip install google-compute-engine

script:
- ./build
- $TRAVIS_BUILD_DIR/travis/install_gcloud.sh

after_success:
- coveralls

before_install:
- $TRAVIS_BUILD_DIR/travis/decrypt.sh
  "$encrypted_ea5d7bea5193_key" "$encrypted_ea5d7bea5193_iv"
  keys/service-accounts.tar.enc /tmp/service-accounts.tar /tmp

# These directories will be cached on successful "script" builds, and restored,
# if available, to save time on future builds.
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

# NOTE: Currently, Prometheus targets are managed in two monitoring groups:
#  1. "scraper" - targets for scraper alerts are generated & deployed by the
#     scraper release process.
#     See more here:
#       https://github.com/m-lab/scraper/blob/master/.travis.yml#L33
#       https://github.com/m-lab/scraper/blob/master/.travis.yml#L48
#
#  2. "global" - targets for all other prometheus usage are generated &
#     deployed by the operator release process.
#
# The monitoring group is the second argument to deploy_prometheus_targets.sh.
deploy:

############################################################################
# Sandbox.
- provider: script
  script: $TRAVIS_BUILD_DIR/deploy_prometheus_targets.sh mlab-sandbox global
  skip_cleanup: true
  on:
    repo: m-lab/operator
    all_branches: true
    condition: $TRAVIS_BRANCH == master || $TRAVIS_BRANCH == sandbox-*

  # Deploy metadata configs.
- provider: script
  script: $TRAVIS_BUILD_DIR/deploy_metadata_configs.sh
      SERVICE_ACCOUNT_mlab_sandbox
      $TRAVIS_BUILD_DIR/gen/mlab-sandbox
      gs://operator-mlab-sandbox/metadata/v0
  skip_cleanup: true
  on:
    repo: m-lab/operator
    all_branches: true
    condition: $TRAVIS_BRANCH == master || $TRAVIS_BRANCH == sandbox-*

############################################################################
# Staging, on master.
- provider: script
  script: $TRAVIS_BUILD_DIR/deploy_prometheus_targets.sh mlab-staging global
  skip_cleanup: true
  on:
    repo: m-lab/operator
    branch: master

  # Deploy metadata configs.
- provider: script
  script: $TRAVIS_BUILD_DIR/deploy_metadata_configs.sh
      SERVICE_ACCOUNT_mlab_staging
      $TRAVIS_BUILD_DIR/gen/mlab-staging
      gs://operator-mlab-staging/metadata/v0
  skip_cleanup: true
  on:
    repo: m-lab/operator
    all_branches: true
    condition: $TRAVIS_BRANCH == master

############################################################################
# Production, on tags.
- provider: script
  script: $TRAVIS_BUILD_DIR/deploy_prometheus_targets.sh mlab-oti global
  skip_cleanup: true
  on:
    repo: m-lab/operator
    tags: true

  # Deploy metadata configs.
- provider: script
  script: $TRAVIS_BUILD_DIR/deploy_metadata_configs.sh
      SERVICE_ACCOUNT_mlab_oti
      $TRAVIS_BUILD_DIR/gen/mlab-oti
      gs://operator-mlab-oti/metadata/v0
  skip_cleanup: true
  on:
    repo: m-lab/operator
    tags: true
